import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import authRoutes from './routes/auth.js';
import subRoutes, { subscriptionWebhook } from './routes/subscription.js';
import barbersRoutes from './routes/barbers.js';
import servicesRoutes from './routes/services.js';
import appointmentsRoutes from './routes/appointments.js';
import reviewsRoutes from './routes/reviews.js';
import paymentsRoutes, { paymentWebhook } from './routes/payments.js';
import shopsRoutes from './routes/shops.js';
import ownersRoutes from './routes/owners.js';

const app = express();
app.use(cors({ origin: true, credentials: true }));
app.post('/api/subscription/webhook', express.raw({ type: 'application/json' }), subscriptionWebhook);
app.post('/api/payments/webhook', express.raw({ type: 'application/json' }), paymentWebhook);
app.use(express.json());
app.get('/health', (_, res) => res.json({ ok: true }));
app.use('/api/auth', authRoutes);
app.use('/api/subscription', subRoutes);
app.use('/api/barbers', barbersRoutes);
app.use('/api', servicesRoutes);
app.use('/api/appointments', appointmentsRoutes);
app.use('/api', reviewsRoutes);
app.use('/api/payments', paymentsRoutes);
app.use('/api/shops', shopsRoutes);
app.use('/api/owners', ownersRoutes);
app.use((err, _, res, __) => { console.error(err); res.status(500).json({ error: 'Server error' }); });
const port = process.env.PORT || 4000;
app.listen(port, () => console.log(`API on ${port}`));
